export const lndStartFlags = `--lnddir=~/electronlnd
--noseedbackup
--nolisten
--bitcoin.active
--bitcoin.regtest
--bitcoin.node=neutrino
--feeurl="https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json"
--routing.assumechanvalid
--tlsdisableautofill
--db.bolt.auto-compact
--db.bolt.auto-compact-min-age=0
--neutrino.connect=localhost:19444`;
